### DISCUSSION TITLE
Wild card type mappings

### DISCUSSION THREAD

**Discussion by lxnre-codes** [gzuidhof/tygo#36] [Ideas]
Using type mapping is very efficient when importing types from external packages, but this becomes really hard to use when importing many types from one package. A less significant case is when updating / adding new types to a shared package. With wild type mapping, this will be easier to use. 

Currently unsure of what wildcard approach makes more sense, but here's an example: 

```go 
// previous SelectorExpr code, write.go `writeType()`
		longType := fmt.Sprintf("%s.%s", t.X, t.Sel)
		mappedTsType, ok := g.conf.TypeMappings[longType]
		if ok {
			s.WriteString(mappedTsType)
		} else { // For unknown types we use the fallback type
			s.WriteString(g.conf.FallbackType)
			s.WriteString(" /* ")
			s.WriteString(longType)
			s.WriteString(" */")
		}
```  

```go
// new SelectorExpr code, write.go `writeType()`
		longType := fmt.Sprintf("%s.%s", t.X, t.Sel)
		mappedTsType, hasMap := g.conf.TypeMappings[longType]
		wildTypeMap, hasWildMap := g.conf.TypeMappings[fmt.Sprintf("%s.*", t.X)]
		switch {
		case hasMap:
			s.WriteString(mappedTsType)
		case hasWildMap:
			s.WriteString(strings.Replace(wildTypeMap, "*", t.Sel.String(), 1))
		default:
			s.WriteString(g.conf.FallbackType)
			s.WriteString(" /* ")
			s.WriteString(longType)
			s.WriteString(" */")
		}
```

```yaml 
# type mapping config
packages:
  - path: "example.com/package"
    fallback_type: unknown
    type_mappings:
      imported.*: "imported.*"
    frontmatter:
      | 
      import * as imported from "imported_package"
```

## Code actions 

- Struct field type mapping comes with the highest preference 
- Wildcard type mapping is used as a fallback if available
