### DISCUSSION TITLE
Is there an intention to support wildcard paths in input/output?

### DISCUSSION THREAD

**Discussion by FirstWhack** [gzuidhof/tygo#9] [Ideas]
For example:

```yaml
packages:
  - path: "github.com/gzuidhof/tygo/models/**/*"
    output_path: "webapp/api/**/*.ts"
    type_mappings:
    # etc. . .
```
