### ISSUE TITLE
Option to not preserve comments

### ISSUE THREAD

**Issue by greyscaled** [gzuidhof/tygo#22]
## Context

By default, `tygo` preserves comments. So for example:

```go
user.go
// package user does xyz
package user

type User struct {
  name: string
}
```

will generate output like:

```ts
//////////
// source: users.go
// package user does xyz

export interface User {
  name: string;
}
```

This is cool behavior, but sometimes it's not desired. Therefore, I think there should be an option
for suppressing comments that do not exist on types. The default would still be to preserve.

## Expected

A config like this:

```yaml
packages:
  - path: "<path>"
    output_path: "<output_path>"
    preserveComments: false # true or false, defaults to true
```

So that Go code like this:

```go
user.go
// package user does xyz
package user

// secret is a secret
const secret = "secret"

type User struct {
  // name is a name
  name: string
}
```

produces TS like this:

```ts
//////////
// source: users.go

export interface User {
  /**
   * name is a name
   */
  name: string;
}
```

## Actual

All comments are preserved and there's no option to suppress this behavior
