### ISSUE TITLE
Fix goreleaser config

### ISSUE THREAD

**Issue by gzuidhof** [gzuidhof/tygo#29]
The latest Github Actions run is broken, I think the config needs to be updated as we were using some outdated config fields that have now been removed.

**Comment by greyscaled** [comment]
```txt
Flag --rm-dist has been deprecated, please use --clean instead
  • starting release...
  • loading config file                              file=goreleaser.yml
  ⨯ release failed after 0s                  error=yaml: unmarshal errors:
  line 14: field replacements not found in type config.Archive
```

https://github.com/gzuidhof/tygo/blob/e7d63ced9801670f68a24331f4a6260a4307201b/goreleaser.yml#L14

It was deprecated and removed as of : `1.19.0`: https://github.com/goreleaser/goreleaser/releases/tag/v1.19.0 in https://github.com/goreleaser/goreleaser/pull/4075

https://github.com/goreleaser/goreleaser/blob/main/www/docs/deprecations.md#archivesreplacements

**Comment by gzuidhof** [comment]
In a different project we use

```yml
archives:
  - id: somename
    name_template: >-
      {{ .ProjectName }}_
      {{- .Tag }}_
      {{- .Os }}_
      {{- .Arch}}
    format_overrides:
      - goos: windows
        format: zip
```

Maybe that will do the job here too :)
