### ISSUE TITLE
Includes (list of files)

### ISSUE THREAD

**Issue by emil14** [gzuidhof/tygo#47]
It would be great to be able to include not the whole package but list of files. I'm aware of "exclude" option but if package is big and I only need 1 file from it, it's error-prone (go package can be changed, list of files it contains changes)

**Comment by emil14** [comment]
Any updates?

**Comment by gzuidhof** [comment]
I'm happy to accept a PR that implements this. I imagine that the package will still have to be specified (that's how the Go compiler/AST-builder works), but we could probably filter after the fact (just like we do for `exclude`).

**Comment by furious-luke** [comment]
Hey @emil14, I was interested in the same functionality and was about to implement it and raise a PR, but I discovered that the functionality already exists. Something like the following works for me:

```yaml
packages:
  - path: "github.com/me/my-test-repo"
    include_files:
      - only_generate_me.go
```
