### ISSUE TITLE
`TypeMappings` usage

### ISSUE THREAD

**Issue by perkrlsn** [gzuidhof/tygo#55]
Given the following simple example.

## Input
```yaml
packages:
  - path: "types/src/test"
    output_path: "src/types.ts"
    type_mappings:
      types.TestType: "number"
```

```go
package types

type TestType string
```

## Output

```typescript
// Code generated by tygo. DO NOT EDIT.

//////////
// source: types.go

export type TestType = string;
```

Any help with the `TypeMappings` feature would be appreciated.
