### ISSUE TITLE
Runes are not converted to numbers

### ISSUE THREAD

**Issue by perkrlsn** [gzuidhof/tygo#56]
Given the following simple example shouldn't `rune` be converted to a `number`?

## Input

```yaml
packages:
  - path: "types/src/test"
    output_path: "src/types.ts"
    type_mappings:
      time.Time: "string /* fancy comment */"
```

```go
package types

import "time"

type TestType string

type TestRune rune

type TestRunes []rune

type TestStruct struct {
	SomeRune *rune
	SomeTime *time.Time
}
```

## Output
```typescript
// Code generated by tygo. DO NOT EDIT.

//////////
// source: types.go

export type TestType = string;
export type TestRune = rune;
export type TestRunes = rune[];
export interface TestStruct {
  SomeRune?: rune;
  SomeTime?: string /* fancy comment */;
}
```
