### ISSUE TITLE
[Proposal] Include only struct fields that contains specified tags

### ISSUE THREAD

**Issue by fkhadra** [gzuidhof/tygo#72]
Hey, currently the only way to exclude some structs from being generated is to provide a list of files to exclude. However, this is not always convenient, often structs live close to the code where they are used.

I'd like to propose an alternative approach. The idea would be to allow the user to generate typescript types only for fields that matches certain struct tags.

In practice, it would looks like this:
```yaml
packages:
    - path: "pathToMyPackage"
    output_path: "src/types/index.ts"
    optional_type: "default"
    # only includes struct fields with a json tag
    match_tags:
      - "json"
```
- Input
```go
package pkg

type User struct {
	Username         string `json:"username"`
	Password          string
}
```
- output
```ts
export interface User {
  username: string;
}
```

For my use case, I'd like to exposes only struct with json tags, I'm currently using a fork of your library for my project https://github.com/fkhadra/tygo. My implementation support any specific struct tag ofc, it's not limited to json.

If you think that this feature is worth adding to your library, I would be happy to open a pull request.

**Comment by gzuidhof** [comment]
Hey @fkhadra,

## Exclude empty structs
Sounds like a great feature :) Happy to accept a PR for that.

## Including fields based on tags
Hmm, also this makes a lot of sense (and it doesn't get in the way for anyone that does not need it).

In the past some have requested a `//tygo:generate` directive (or something like that), or `//tygo:include` & `//tygo:exclude`).  I can see this being added to `tygo` at some point, I'm not sure how it should/would interact with this. Maybe the config should have a config field for include or exclude that have some subfields?

I'm not sure what the best UX is 🤔 What do you think? Writing it out maybe we should keep it simple and not add this `include/exclude` grouping..

```yml
packages:
    - path: "pathToMyPackage"
    output_path: "src/types/index.ts"
    optional_type: "default"
    include:
      match_tags:
        - "json"
    exclude:
       empty_structs: true #Or maybe this is a bit weird?
```
