### ISSUE TITLE
Multiple pagakes with various types into one file

### ISSUE THREAD

**Issue by shortcircuit3** [gzuidhof/tygo#75]
I have a repo with a few packages. I'm trying to generate golang types for the full project but i can't seem to find a way to link the types. For example, see the `user` type reference. The type is in another package, but I want this type to be connected in the tygo generated file.

Any advice?

```
export interface LoginResponse {
  access_token: string;
  refresh_token: string;
  user?: any /* models.User */;
}
export interface VerifyAccountResponse {
  access_token: string;
  refresh_token: string;
  user?: any /* models.User */;
}
```

**Comment by VeryEvilHumna** [comment]
I think you already found a solution, but I still leave mine there for ones who had the same issue. 

I had the same issue, ended up solving it with a bash script (a task for a task runner actually) that merges all files in a directory to one big `index.d.ts`. 

But you can include a tag in the filename of emitted ts file for some modules and  `user.requestGroup.ts`, `requests.requestGroup.ts`, then merge files that had the same tag.

## My solution

```bash
# generate_types.sh

cd ./backend
tygo generate
cd ../frontend/.tygo_types
cat *.temp.ts > index.d.ts
rm *.temp.ts
```

```yaml
# tygo.yaml

packages:
  - path: "example.com/requests"
    output_path: "../frontend/.tygo_types/requests.temp.ts"
  - path: "example.com/user"
    output_path: "../frontend/.tygo_types/user.temp.ts"
  - path: "example.com/auth"
    output_path: "../frontend/.tygo_types/auth.temp.ts"
```

That's not the most elegant solution, but the simplest one at least. The resulting file looks a bit ugly, because `Code generated by tygo. DO NOT EDIT.` is repeated for every module, but it works just fine. I hope this helps.

P.S. The feature of merging types from modules in one file seems essential, and it would be great if that would be a built-in feature of tygo.
